- name: 'configure dotfiles'
  hosts: all
  tasks:
    - name: 'install rsync'
      become: true
      ansible.builtin.apt:
        name:
          - 'rsync'

    - name: 'sync dotfiles'
      ansible.posix.synchronize:
        src: 'dotfiles/'
        dest: '.'
        times: false
