- name: 'configure gastrak'
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: 'install sqlite'
      ansible.builtin.apt:
        name:
          - 'sqlite3'

    - name: 'install go'
      ansible.builtin.apt:
        name:
          - 'golang'
        state: latest
        default_release: '{{ ansible_distribution_release }}-backports'

    - name: 'create gastrak group'
      ansible.builtin.group:
        name: 'gastrak'

    - name: 'create gastrak user'
      ansible.builtin.user:
        name: 'gastrak'
        group: 'gastrak'
        shell: '/bin/bash'

    - name: 'create .ssh directory'
      ansible.builtin.file:
        path: '/home/gastrak/.ssh'
        state: directory
        owner: 'gastrak'
        group: 'gastrak'
        mode: '0700'

    - name: 'disable ssh host key checking'
      ansible.builtin.copy:
        dest: '/home/gastrak/.ssh/config'
        owner: 'gastrak'
        group: 'gastrak'
        content: |
          Host github.com
            HostName github.com
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null

    - name: 'add deploy ssh private key'
      ansible.builtin.copy:
        dest: '/home/gastrak/.ssh/id_ed25519'
        owner: 'gastrak'
        group: 'gastrak'
        mode: '0600'
        content: "{{ lookup('ansible.builtin.pipe', 'pass ssh/gastrak@' + hostname | quote) }}\n"

    - name: 'add deploy ssh public key'
      ansible.builtin.copy:
        dest: '/home/gastrak/.ssh/id_ed25519.pub'
        owner: 'gastrak'
        group: 'gastrak'
        content: "{{ lookup('ansible.builtin.pipe', 'pass ssh/gastrak@' + hostname | quote + '.pub') }}\n"

    - name: 'set git user.name'
      become_user: 'gastrak'
      ansible.builtin.git_config:
        scope: global
        name: 'user.name'
        value: 'gastrak'

    - name: 'set git user.email'
      become_user: 'gastrak'
      ansible.builtin.git_config:
        scope: global
        name: 'user.email'
        value: 'gastrak@{{ hostname }}.{{ domain_name }}'

    - name: 'clone code repo'
      become_user: 'gastrak'
      notify:
        - 'restart gastrak service'
        - 'restart gastrak-refresh timer'
      ansible.builtin.git:
        repo: 'https://github.com/apsun/gastrak.git'
        dest: '/home/gastrak/gastrak'

    - name: 'clone data repo'
      become_user: 'gastrak'
      register: gastrak_data_repo
      ansible.builtin.git:
        repo: 'git@github.com:apsun/gastrak-data.git'
        dest: '/home/gastrak/gastrak/data'
        update: false

    - name: 'initialize data'
      become_user: 'gastrak'
      when: gastrak_data_repo.changed
      ansible.builtin.command:
        cmd: '/home/gastrak/gastrak/gastrak/run-gastrak.sh'

    - name: 'create gastrak service'
      notify: 'restart gastrak service'
      ansible.builtin.copy:
        src: 'gastrak.service'
        dest: '/etc/systemd/system/gastrak.service'

    - name: 'enable gastrak service'
      ansible.builtin.systemd:
        name: 'gastrak'
        state: started
        enabled: true
        daemon_reload: true

    - name: 'create gastrak-refresh service'
      notify: 'restart gastrak-refresh timer'
      ansible.builtin.copy:
        src: 'gastrak-refresh.service'
        dest: '/etc/systemd/system/gastrak-refresh.service'

    - name: 'create gastrak-refresh timer'
      notify: 'restart gastrak-refresh timer'
      ansible.builtin.copy:
        src: 'gastrak-refresh.timer'
        dest: '/etc/systemd/system/gastrak-refresh.timer'

    - name: 'enable gastrak-refresh timer'
      ansible.builtin.systemd:
        name: 'gastrak-refresh.timer'
        state: started
        enabled: true
        daemon_reload: true

  handlers:
    - name: 'restart gastrak service'
      ansible.builtin.systemd:
        name: 'gastrak'
        state: restarted
        daemon_reload: true

    - name: 'restart gastrak-refresh timer'
      ansible.builtin.systemd:
        name: 'gastrak-refresh.timer'
        state: restarted
        daemon_reload: true
