- name: 'configure gastrak'
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: 'install go'
      ansible.builtin.apt:
        name:
          - 'golang'
        state: latest
        default_release: '{{ ansible_distribution_release }}-backports'

    - name: 'create gastrak group'
      ansible.builtin.group:
        name: 'gastrak'

    - name: 'create gastrak user'
      ansible.builtin.user:
        name: 'gastrak'
        group: 'gastrak'
        shell: '/bin/bash'

    - name: 'clone git repo'
      become_user: 'gastrak'
      notify:
        - 'restart gastrak service'
        - 'restart gastrak-refresh timer'
      ansible.builtin.git:
        repo: 'https://github.com/apsun/gastrak.git'
        dest: '/home/gastrak/gastrak'

    - name: 'check if already initialized'
      become_user: 'gastrak'
      register: gastrak_initialized
      ansible.builtin.stat:
        path: '/home/gastrak/gastrak/data/current.csv'

    - name: 'initialize data'
      become_user: 'gastrak'
      when: not gastrak_initialized.stat.exists
      ansible.builtin.command:
        cmd: '/home/gastrak/gastrak/data/run-gastrak.sh'

    - name: 'create gastrak service'
      notify: 'restart gastrak service'
      ansible.builtin.copy:
        src: 'gastrak.service'
        dest: '/etc/systemd/system/gastrak.service'

    - name: 'enable gastrak service'
      ansible.builtin.systemd:
        name: 'gastrak'
        state: started
        enabled: true
        daemon_reload: true

    - name: 'create gastrak-refresh service'
      notify: 'restart gastrak-refresh timer'
      ansible.builtin.copy:
        src: 'gastrak-refresh.service'
        dest: '/etc/systemd/system/gastrak-refresh.service'

    - name: 'create gastrak-refresh timer'
      notify: 'restart gastrak-refresh timer'
      ansible.builtin.copy:
        src: 'gastrak-refresh.timer'
        dest: '/etc/systemd/system/gastrak-refresh.timer'

    - name: 'enable gastrak-refresh timer'
      ansible.builtin.systemd:
        name: 'gastrak-refresh.timer'
        state: started
        enabled: true
        daemon_reload: true

  handlers:
    - name: 'restart gastrak service'
      ansible.builtin.systemd:
        name: 'gastrak'
        state: restarted
        daemon_reload: true

    - name: 'restart gastrak-refresh timer'
      ansible.builtin.systemd:
        name: 'gastrak-refresh.timer'
        state: restarted
        daemon_reload: true
