- name: 'configure dns'
  hosts: all
  gather_facts: false
  vars:
    enable_dns: true
    fqdn: '{{ hostname }}.{{ domain_name }}'
    public_ip: '{{ inventory_hostname }}'
    cloudflare_api_token: '{{ lookup("ansible.builtin.pipe", "pass cloudflare.com/{{ domain_name }}-edit-dns-api-token") }}'

  tasks:
    - name: 'add A record'
      when: enable_dns
      community.general.cloudflare_dns:
        state: present
        api_token: '{{ cloudflare_api_token }}'
        zone: '{{ domain_name }}'
        type: 'A'
        record: '{{ hostname }}'
        value: '{{ public_ip }}'
        solo: true

    - name: 'add CNAME record (sub)'
      when: enable_dns
      community.general.cloudflare_dns:
        state: present
        api_token: '{{ cloudflare_api_token }}'
        zone: '{{ domain_name }}'
        type: 'CNAME'
        record: '*'
        value: '{{ fqdn }}'
        solo: true

    - name: 'add CNAME record (root)'
      when: enable_dns
      community.general.cloudflare_dns:
        state: present
        api_token: '{{ cloudflare_api_token }}'
        zone: '{{ domain_name }}'
        type: 'CNAME'
        record: '@'
        value: '{{ fqdn }}'
        solo: true

    - name: 'delete CNAME record (root)'
      when: not enable_dns
      community.general.cloudflare_dns:
        state: absent
        api_token: '{{ cloudflare_api_token }}'
        zone: '{{ domain_name }}'
        type: 'CNAME'
        record: '@'

    - name: 'delete CNAME record (sub)'
      when: not enable_dns
      community.general.cloudflare_dns:
        state: absent
        api_token: '{{ cloudflare_api_token }}'
        zone: '{{ domain_name }}'
        type: 'CNAME'
        record: '*'

    - name: 'delete A record'
      when: not enable_dns
      community.general.cloudflare_dns:
        state: absent
        api_token: '{{ cloudflare_api_token }}'
        zone: '{{ domain_name }}'
        type: 'A'
        record: '{{ hostname }}'
