- name: 'configure nginx'
  hosts: all
  become: true
  gather_facts: true
  vars:
    enable_ssl: true

  tasks:
    - name: 'install gpg'
      ansible.builtin.apt:
        name:
          - 'gpg'

    - name: 'add nginx signing key'
      ansible.builtin.apt_key:
        url: 'https://nginx.org/keys/nginx_signing.key'

    - name: 'add nginx repo'
      ansible.builtin.apt_repository:
        repo: 'deb https://nginx.org/packages/mainline/debian {{ ansible_distribution_release }} nginx'

    - name: 'configure nginx repo priority'
      ansible.builtin.copy:
        dest: '/etc/apt/preferences.d/99-nginx'
        content: |
          Package: *
          Pin: origin nginx.org
          Pin: release o=nginx
          Pin-Priority: 900

    - name: 'install nginx'
      ansible.builtin.apt:
        name:
          - 'nginx'
        update_cache: true

    - name: 'create ssl-dhparams.pem'
      notify: 'restart nginx service'
      ansible.builtin.copy:
        src: 'ssl-dhparams.pem'
        dest: '/etc/letsencrypt/ssl-dhparams.pem'

    - name: 'create nginx-restart service'
      notify: 'restart nginx-restart timer'
      ansible.builtin.copy:
        src: 'nginx-restart.service'
        dest: '/etc/systemd/system/nginx-restart.service'

    - name: 'create nginx-restart timer'
      notify: 'restart nginx-restart timer'
      ansible.builtin.copy:
        src: 'nginx-restart.timer'
        dest: '/etc/systemd/system/nginx-restart.timer'

    - name: 'create letsencrypt conf'
      notify: 'restart nginx service'
      ansible.builtin.template:
        src: 'letsencrypt.conf.j2'
        dest: '/etc/letsencrypt/options-ssl-nginx.conf'

    - name: 'create nginx-signal-relay service'
      notify: 'restart nginx-signal-relay service'
      ansible.builtin.copy:
        src: 'nginx-signal-relay.service'
        dest: '/etc/systemd/system/nginx-signal-relay.service'

    - name: 'download nginx-signal-relay.conf'
      notify: 'restart nginx-signal-relay service'
      ansible.builtin.get_url:
        url: 'https://raw.githubusercontent.com/signalapp/Signal-TLS-Proxy/main/data/nginx-relay/nginx.conf'
        dest: '/etc/nginx/nginx-signal-relay.conf'

    - name: 'create nginx.conf'
      notify: 'restart nginx service'
      ansible.builtin.template:
        src: 'nginx.conf.j2'
        dest: '/etc/nginx/nginx.conf'

    - name: 'enable nginx service'
      when: enable_ssl
      ansible.builtin.systemd:
        name: 'nginx'
        state: started
        enabled: true

    - name: 'enable nginx-signal-relay service'
      when: enable_ssl
      ansible.builtin.systemd:
        name: 'nginx-signal-relay'
        state: started
        enabled: true
        daemon_reload: true

    - name: 'enable nginx-restart timer'
      when: enable_ssl
      ansible.builtin.systemd:
        name: 'nginx-restart.timer'
        state: started
        enabled: true
        daemon_reload: true

    - name: 'disable nginx service'
      when: not enable_ssl
      ansible.builtin.systemd:
        name: 'nginx'
        state: stopped
        enabled: false

    - name: 'disable nginx-signal-relay service'
      when: not enable_ssl
      ansible.builtin.systemd:
        name: 'nginx-signal-relay'
        state: stopped
        enabled: false
        daemon_reload: true

    - name: 'disable nginx-restart timer'
      when: not enable_ssl
      ansible.builtin.systemd:
        name: 'nginx-restart.timer'
        state: stopped
        enabled: false
        daemon_reload: true

  handlers:
    - name: 'restart nginx service'
      when: enable_ssl
      ansible.builtin.systemd:
        name: 'nginx'
        state: restarted
        daemon_reload: true

    - name: 'restart nginx-signal-relay service'
      when: enable_ssl
      ansible.builtin.systemd:
        name: 'nginx-signal-relay'
        state: restarted
        daemon_reload: true

    - name: 'restart nginx-restart timer'
      ansible.builtin.systemd:
        name: 'nginx-restart.timer'
        state: restarted
        daemon_reload: true
