- name: 'configure apache'
  hosts: all
  become: true
  vars:
    enable_ssl: true

    modules:
      - 'proxy'
      - 'proxy_http'
      - 'proxy_wstunnel'
      - 'rewrite'
      - 'ssl'

    sites:
      - '000-default'
      - '001-index'
      - '003-clips'
      - '004-gastrak'
      - '005-fish'

    sites_disabled:
      - '002-send'

  tasks:
    - name: 'install apache'
      ansible.builtin.apt:
        name:
          - 'apache2'

    - name: 'enable modules'
      loop: '{{ modules }}'
      register: mod_result
      changed_when: '"Module " + item + " already enabled" not in mod_result.stdout'
      notify: 'restart apache service'
      ansible.builtin.shell:
        cmd: 'a2enmod {{ item }}'

    - name: 'create index.html'
      ansible.builtin.template:
        src: 'index.html.j2'
        dest: '/var/www/html/index.html'

    - name: 'create letsencrypt.conf'
      notify: 'restart apache service'
      ansible.builtin.template:
        src: 'letsencrypt.conf.j2'
        dest: '/etc/letsencrypt/options-ssl-apache.conf'

    - name: 'modify ports.conf'
      notify: 'restart apache service'
      ansible.builtin.copy:
        src: 'ports.conf'
        dest: '/etc/apache2/ports.conf'

    - name: 'create site configs'
      loop: '{{ sites + sites_disabled }}'
      notify: 'restart apache service'
      ansible.builtin.template:
        src: 'sites/{{ item }}.conf.j2'
        dest: '/etc/apache2/sites-available/{{ item }}.conf'

    - name: 'disable old site configs'
      loop: '{{ sites_disabled }}'
      register: disable_site_result
      changed_when: '"Site " + item + " already disabled" not in disable_site_result.stdout'
      notify: 'restart apache service'
      ansible.builtin.shell:
        cmd: 'a2dissite {{ item }}'

    - name: 'enable site configs'
      loop: '{{ sites }}'
      register: site_result
      changed_when: '"Site " + item + " already enabled" not in site_result.stdout'
      notify: 'restart apache service'
      ansible.builtin.shell:
        cmd: 'a2ensite {{ item }}'

    - name: 'enable apache service'
      ansible.builtin.systemd:
        name: 'apache2'
        state: started
        enabled: true

  handlers:
    - name: 'restart apache service'
      ansible.builtin.systemd:
        name: 'apache2'
        state: restarted
