- name: 'configure letsencrypt'
  hosts: all
  become: true
  vars:
    enable_ssl: true
    fqdn: '{{ hostname }}.{{ domain_name }}'
    public_ip: '{{ inventory_hostname }}'
    cloudflare_api_token: '{{ lookup("ansible.builtin.pipe", "pass cloudflare.com/{{ domain_name }}-edit-dns-api-token") }}'
    letsencrypt_email: '{{ lookup("ansible.builtin.pipe", "pass letsencrypt.org/email") }}'

  tasks:
    - name: 'install certbot'
      ansible.builtin.apt:
        name:
          - 'certbot'
          - 'python3-certbot-dns-cloudflare'

    - name: 'create certbot secrets directory'
      ansible.builtin.file:
        path: '/root/.secrets/certbot'
        state: directory
        mode: '0700'

    - name: 'write cloudflare API token'
      ansible.builtin.template:
        src: 'cloudflare.ini.j2'
        dest: '/root/.secrets/certbot/cloudflare.ini'
        mode: '0600'

    - name: 'check if cert already exists'
      register: letsencrypt_initialized
      ansible.builtin.stat:
        path: '/etc/letsencrypt/renewal/{{ fqdn }}.conf'

    - name: 'request new cert'
      when: enable_ssl and not letsencrypt_initialized.stat.exists
      ansible.builtin.shell:
        cmd: >-
          certbot certonly
          --non-interactive
          --agree-tos
          --email {{ letsencrypt_email }}
          --dns-cloudflare
          --dns-cloudflare-credentials /root/.secrets/certbot/cloudflare.ini
          --domains *.{{ fqdn }},{{ fqdn }}

    - name: 'enable certbot renew timer'
      ansible.builtin.systemd:
        name: 'certbot.timer'
        state: started
        enabled: true
