- name: 'configure packages'
  hosts: all
  become: true
  tasks:
    - name: 'update all packages'
      ansible.builtin.apt:
        name: '*'
        state: latest
        update_cache: true

    - name: 'install useful utilities'
      ansible.builtin.apt:
        name:
          - 'vim'
          - 'tree'
          - 'tmux'
          - 'jq'
          - 'ripgrep'
          - 'htop'
          - 'strace'
          - 'ldnsutils'

    - name: 'choose vim as editor'
      community.general.alternatives:
        name: 'editor'
        path: '/usr/bin/vim.basic'
