- name: 'configure packages'
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: 'add backports repo'
      ansible.builtin.apt_repository:
        repo: 'deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main'

    - name: 'update all packages'
      ansible.builtin.apt:
        name: '*'
        state: latest
        update_cache: true

    - name: 'install useful utilities'
      ansible.builtin.apt:
        name:
          - 'acl'  # needed for become_user
          - 'git'
          - 'vim'
          - 'tree'
          - 'tmux'
          - 'jq'
          - 'ripgrep'
          - 'htop'
          - 'strace'
          - 'ldnsutils'

    - name: 'choose vim as editor'
      community.general.alternatives:
        name: 'editor'
        path: '/usr/bin/vim.basic'
