- name: 'configure packages'
  hosts: all
  become: true
  tasks:
    - name: 'update all packages'
      ansible.builtin.apt:
        name: '*'
        state: latest
        update_cache: true

    - name: 'install useful utilities'
      ansible.builtin.apt:
        name:
          - 'tree'
          - 'tmux'
          - 'jq'
          - 'ripgrep'
          - 'htop'
          - 'strace'
          - 'ldnsutils'
